name = "twitter-proxy"
main = "dist/index.js"
compatibility_date = "2023-10-30"
node_compat = true

[build]
command = "npm run build"

[vars]
ALLOWED_ORIGINS = ""
# REDIS_URL = "" # Uncomment and set this to your Upstash Redis URL in production

[[kv_namespaces]]
binding = "TOKENS"
id = "tokens-id-placeholder"
preview_id = "tokens-preview-id-placeholder"

[[d1_databases]]
binding = "DB"
database_name = "twitter-proxy"
database_id = "db-id-placeholder"
preview_database_id = "db-preview-id-placeholder"

[env.staging]
name = "twitter-proxy-staging"
vars = { ENVIRONMENT = "staging" }
# vars = { ENVIRONMENT = "staging", REDIS_URL = "" } # Uncomment and set REDIS_URL in production

[env.production]
name = "twitter-proxy-production"
vars = { ENVIRONMENT = "production" }
# vars = { ENVIRONMENT = "production", REDIS_URL = "" } # Uncomment and set REDIS_URL in production
