name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache dependencies
        run: deno cache deps.ts

      - name: Format check
        run: deno fmt --check

      # - name: Lint
      #   run: deno lint

      - name: Run tests
        run: deno task test

  # deploy-staging:
  #   needs: test
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #     contents: read

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Deno
  #       uses: denoland/setup-deno@v1
  #       with:
  #         deno-version: v1.x

  #     - name: Deploy to Deno Deploy
  #       uses: denoland/deployctl@v1
  #       with:
  #         project: "open-crosspost-proxy-staging"
  #         entrypoint: "main.ts"
  #         import-map: "./deno.json"
  #       env:
  #         DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
  #         ENVIRONMENT: staging
