name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        working-directory: packages
        
      # Build and publish @crosspost/types
      - name: Build types package
        run: npm run build
        working-directory: packages/types
        
      - name: Publish types package
        run: npm publish
        working-directory: packages/types
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          
      # Build and publish @crosspost/sdk
      - name: Build SDK package
        run: npm run build
        working-directory: packages/sdk
        
      - name: Publish SDK package
        run: npm publish
        working-directory: packages/sdk
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
