name: Publish to JSR

on:
  release:
    types: [created]

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: npm ci
        working-directory: packages

      # Publish @crosspost/types to JSR
      - name: Publish types to JSR
        run: deno publish
        working-directory: packages/types

      # Publish @crosspost/sdk to JSR
      - name: Publish SDK to JSR
        run: deno publish
        working-directory: packages/sdk
